### PR TITLE
notes on eBPF probe

### PR DESCRIPTION
**Pull request by steveww**
Some extra notes on the eBPF probe.

### CODE REVIEW

**Comment by arramos84** [comment]
Looks good, just need to bump the chart minor version

**Comment by steveww** [comment]
Do you want me to bump the version or are you going to do it?

**Comment by arramos84** [comment]
> > Do you want me to bump the version or are you going to do it?
> 
> > Do you want me to bump the version or are you going to do it?
> 
> You can do it.

Just bumped it

**Comment by arramos84** [comment]
Accidentally closed this

**Review by jgehrett — APPROVED** [review]

**Pull request merged**
